# Generated by Django 3.2.5 on 2022-01-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakemovieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='adafdafs', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
